Repository blitz-js/blitzjs.com, pull requests merged in 2021-01, with the labels that each got.

#295 fix: fix outdated & incorrect code example
  docs/tutorial.mdx
Labels: status/done

#297 tutorial db migration cosmetics
  docs/tutorial.mdx
Labels: status/in-review

#298 Add missing types to SessionConfig
  docs/session-management.mdx
Labels: status/in-review

#299 Add docs for SecurePassword
  docs/auth-utils.mdx
  sidebars.js
Labels: 0 - <(^_^)> - merge it! ✌️, status/in-review

#172 Fix how to cli development
  docs/contributing.mdx
Labels: status/in-review

#307 Add docs for custom server
  docs/custom-server.mdx
  sidebars.js
Labels: status/in-review

#308 Add docs for `blitz prisma` command
  docs/cli-prisma.mdx
  sidebars.js
Labels: status/in-review

#310 Improve the passport strategy docs
  docs/passportjs.mdx
Labels: status/in-review

#309 Roll back the sentence to the original output
  docs/tutorial.mdx
Labels: status/in-review

#312 Add more docs on running postgres locally
  docs/database-overview.mdx
  docs/postgres.mdx
  sidebars.js
Labels: 0 - <(^_^)> - merge it! ✌️, status/in-review

#313 Add link to prisma data guide from db page
  docs/database-overview.mdx
Labels: 0 - <(^_^)> - merge it! ✌️, status/in-review

#314 Update image docs for next.js 10.0.5
  docs/image-optimization.mdx
Labels: 0 - <(^_^)> - merge it! ✌️, status/in-review

#319 Improve session management docs including a TLDR section at the top
  docs/session-management.mdx
Labels: 0 - <(^_^)> - merge it! ✌️, status/in-review

#315 Polish the tutorial to make it more precise
  docs/tutorial.mdx
Labels: status/in-review

#321 Update docs for prisma 2.13+ support
  docs/cli-db.mdx
  docs/database-overview.mdx
  docs/deploy-heroku.mdx
  docs/deploy-render.mdx
  docs/deploy-vercel.mdx
  docs/tutorial.mdx
Labels: status/in-review

#311 V2 - extract out <Footer>
  new-site/app/components/home/Footer.js
  new-site/app/pages/index.js
Labels: status/in-review

#322 V2 - Banner
  new-site/app/components/Banner.js
  new-site/app/components/Header.js
  new-site/app/pages/index.js
  new-site/tailwind.config.js
Labels: status/in-review

#301 V2 - Custom Document
  new-site/app/pages/_document.js
  new-site/public/128x128-Favicon-Black.png
  new-site/public/128x128-Favicon-Dark_Purple.png
  new-site/public/128x128-Favicon-Purple.png
  new-site/public/16x16-Favicon-Purple.png
  new-site/public/32x32-Favicon-Black.png
  new-site/public/32x32-Favicon-Dark_Purple.png
  new-site/public/32x32-Favicon-Purple.png
  new-site/public/android-chrome-192x192.png
  new-site/public/android-chrome-512x512.png
  new-site/public/apple-touch-icon.png
  new-site/public/manifest.json
  new-site/public/safari-pinned-tab.svg
Labels: status/in-review

#327 add docs for hash256() and generateToken()
  docs/auth-utils.mdx
Labels: status/in-review

#317 New site homepage bugfix
  new-site/app/components/ButtonLink.js
  new-site/app/components/NavLink.js
  new-site/app/components/Search.js
  new-site/app/components/home/Icon.js
  new-site/app/components/home/Sponsor.js
  new-site/app/components/home/StyledLink.js
  new-site/app/pages/index.js
Labels: status/in-review

#328 Fixed dark mode toggle on page load
  new-site/app/components/DarkModeToggle.js
Labels: status/in-review

#325 Update docs for new file structure
  docs/cli-generate.mdx
  docs/file-structure.mdx
  docs/tutorial.mdx
  docs/why-blitz.mdx
Labels: status/in-review

#326 Add docs for `makeServerOnlyPrisma()`
  docs/prisma.mdx
  sidebars.js
Labels: status/in-review

#330 Add myself as L1 Maintainer
  docs/how-the-community-operates.mdx
Labels: status/in-review

#331 Improve tutorial doc
  docs/tutorial.mdx
Labels: status/in-review

#333 update recipe examples
  docs/why-blitz.mdx
Labels: status/in-review

#329 add docs for new jest integration
  docs/file-structure.mdx
  docs/testing.mdx
  sidebars.js
Labels: status/in-review

#334 docs for makeServerOnlyPrisma -> enhancePrisma
  docs/prisma.mdx
Labels: status/in-review

#335 Mention "transformPlain"
  docs/writing-recipes.mdx
Labels: status/in-review

#337 rename chakra recipe to chakra-ui
  src/pages/index.js
Labels: status/in-review

#338 Update slack info for maintainers
  docs/maintainers.mdx
Labels: status/in-review

#336 Add Hands to Homepage
  new-site/app/components/CodeWindow.js
  new-site/app/components/home/Footer.js
  new-site/app/components/home/Hand.js
  new-site/app/components/home/HeroCode.js
  new-site/app/components/home/Icon.js
  new-site/app/css/main.css
  new-site/app/pages/index.js
  new-site/public/img/architecture.svg
  new-site/tailwind.config.js
Labels: status/in-review

#340 Update docs for new ctx.session syntax
  docs/authorization.mdx
  docs/session-management.mdx
  docs/tutorial.mdx
  new-site/app/components/CodeWindow.js
  new-site/app/components/home/Footer.js
  new-site/app/components/home/Hand.js
  new-site/app/components/home/HeroCode.js
  new-site/app/components/home/Icon.js
  new-site/app/css/main.css
  new-site/app/pages/index.js
  new-site/public/img/architecture.svg
  new-site/tailwind.config.js
Labels: status/in-review

#341 Update docs for new isAuthorized improvements
  docs/authorization.mdx
  docs/session-management.mdx
Labels: status/in-review

#342 Add docs for all the new `pipe` utilities
  docs/invoke.mdx
  docs/mutation-resolvers.mdx
  docs/query-resolvers.mdx
  docs/resolver-client-utilities.mdx
  docs/resolver-server-utilities.mdx
  sidebars.js
Labels: status/in-review

#339 Fix typo in session-management.mdx and code block in document-component.mdx
  docs/document-component.mdx
  docs/session-management.mdx
Labels: status/in-review

#344 Update docs for PublicData changes
  docs/session-management.mdx
Labels: status/in-review

#345 Fix invalid DOM property warnings
  new-site/app/components/home/Hand.js
Labels: status/in-review

#347 Mention API Routes in RPC spec
  docs/rpc-specification.mdx
Labels: status/in-review

#348 update canary docs for `pipe.resolver` rename to `resolver.pipe`
  docs/resolver-server-utilities.mdx
Labels: status/in-review

#349 Remove docs for `resolver.authorizeIf` and `session.$authorize()`
  docs/authorization.mdx
  docs/resolver-server-utilities.mdx
Labels: status/in-review
