Repository blitz-js/blitzjs.com, pull requests merged in 2022-08, with the labels that each got.

#715 Add Placemark to showcase
  app/core/utils/showcaseList.js
  public/showcase/placemark.png
Labels: status/in-review

#716 Update Tutorial's folder structure
  app/pages/docs/tutorial.mdx
Labels: status/in-review

#718 Add missing pages to the docs
  app/core/navs/documentation.json
  app/pages/docs/impersonation.mdx
  app/pages/docs/multitenancy.mdx
Labels: status/in-review

#719 Mention queries cancellation in the docs
  app/pages/docs/query-usage.mdx
Labels: status/in-review

#722 Remove very outdated video from how to contribute page
  app/pages/docs/contributing.mdx
Labels: status/in-review, 0 - <(^_^)> - merge it! ✌️

#724 fix typo in seed command
  app/pages/docs/database-seeds.mdx
Labels: status/done

#725 Fix gSSP usage example in session management
  app/pages/docs/session-management.mdx
Labels: status/in-review

#723 Documentation for the new BlitzServerMiddleware function
  app/core/navs/documentation.json
  app/pages/docs/middleware.mdx
  app/pages/docs/utilities.mdx
Labels: status/in-review

#729 Add updated Blitz 2.0 tutorial
  app/core/navs/documentation.json
  app/pages/docs/tutorial.mdx
Labels: status/in-review

#730 Update sponors list
  app/core/components/SponsorPack.js
Labels: status/in-review

#727 Update the homepage hero code to Blitz Toolkit
  app/core/components/home/HeroCode.js
Labels: status/in-review

#733 Update packages versions mentioned in docs
  app/pages/docs/blitz-with-next.mdx
  app/pages/docs/get-started.mdx
  app/pages/docs/upgrading-from-framework.mdx
Labels: status/in-review

#734 Update codemod docs
  app/pages/docs/upgrading-from-framework.mdx
Labels: status/in-review

#735 Update CTA link
  app/core/navs/documentation.json
  app/pages/index.js
Labels: status/in-review

#736 Update link to @blitzjs/next adapter
  app/pages/docs/blitz-with-next.mdx
Labels: status/in-review

#737 Add product hire.win to showcase
  app/core/utils/showcaseList.js
  public/showcase/hire-win.png
Labels: status/in-review

#739 Remove mention of custom templates until we add them back
  app/pages/docs/cli-generate.mdx
  app/pages/docs/custom-server.mdx
Labels: status/in-review

#740 Fixes broken link in upgrading-from-framework
  app/pages/docs/upgrading-from-framework.mdx
Labels: status/in-review

#741 Update templates.mdx
  app/pages/docs/templates.mdx
Labels: status/in-review

#726 Add @orionmiz as L2 maintainer
  app/pages/docs/how-the-community-operates.mdx
Labels: status/in-review

#738 Update tutorial.mdx - fix variable name
  app/pages/docs/tutorial.mdx
Labels: status/in-review

#732 Update file-structure.mdx to Blitz Toolkit Structure
  app/pages/docs/file-structure.mdx
Labels: status/in-review

#728 Fix imports and wrappers in the docs
  app/pages/docs/query-usage.mdx
  app/pages/docs/use-paginated-query.mdx
Labels: status/in-review

#744 Change fungarzione name to glink
  app/core/utils/showcaseList.js
Labels: status/in-review

#742 Update docs around env variables
  app/core/navs/documentation.json
  app/pages/docs/cli-build.mdx
  app/pages/docs/cli-codegen.mdx
  app/pages/docs/cli-console.mdx
  app/pages/docs/cli-db.mdx
  app/pages/docs/cli-dev.mdx
  app/pages/docs/cli-export.mdx
  app/pages/docs/cli-generate.mdx
  app/pages/docs/cli-install.mdx
  app/pages/docs/cli-new.mdx
  app/pages/docs/cli-prisma.mdx
  app/pages/docs/cli-start.mdx
  app/pages/docs/custom-environments.mdx
  app/pages/docs/deploy-vercel.mdx
  app/pages/docs/environment-variables.mdx
Labels: status/in-review

#745 Remove any trace of `invokeWithCtx`
  app/pages/docs/query-usage.mdx
  app/pages/docs/resolver-server-utilities.mdx
Labels: status/in-review

#746 fix: unable to drag the scroll over the hand
  app/core/styles/main.css
Labels: status/in-review

#751 import getAntiCSRFToken from @blitzjs/auth
  app/pages/docs/upgrading-from-framework.mdx
Labels: status/in-review

#743 Update eslint-config.mdx to the Blitz Tooklit configuration
  app/pages/docs/eslint-config.mdx
Labels: status/in-review

#749 Add AuthenticatedSessionContext to import map in upgrade page
  app/pages/docs/upgrading-from-framework.mdx
Labels: status/in-review

#748 improved Image component document for Blitz 2.0
  app/pages/docs/image-component.mdx
Labels: status/in-review

#747 Add docs for custom strategy name
  app/pages/docs/passportjs.mdx
Labels: status/in-review
